# Generated by Django 4.1.2 on 2025-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0004_auto_20201124_0614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="key",
            field=models.SlugField(unique=True),
        ),
    ]
