# Generated by Django 4.1.2 on 2025-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0005_alter_siteconfig_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
