# Generated by Django 4.1.2 on 2025-03-19 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0006_siteconfig_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="description",
        ),
    ]
