# Generated by Django 5.2 on 2025-04-17 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0012_themesettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ThemeSettings",
        ),
    ]
