# Generated by Django 4.1.2 on 2025-11-14 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="noticerecipient",
            name="unique_notice_user",
        ),
        migrations.AlterField(
            model_name="notice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="noticecategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="noticerecipient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noticerecipient",
            unique_together={("notice", "user")},
        ),
    ]
