# Generated by Django 5.1.6 on 2025-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='other_name',
        ),
    ]
