# Generated by Django 5.1.6 on 2025-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_remove_staff_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Subspecification',
            field=models.TextField(blank=True),
        ),
    ]
