# Generated by Django 5.1.6 on 2025-03-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_staff_subspecification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Subspecification',
            new_name='Subject_specification',
        ),
    ]
