# Generated by Django 5.1.6 on 2025-03-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_rename_subspecification_staff_subject_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='date_of_admission',
            new_name='date_of_reg',
        ),
    ]
