# Generated by Django 5.1.6 on 2025-03-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_rename_date_of_admission_staff_date_of_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='date_of_reg',
            new_name='date_of_registration',
        ),
    ]
