# Generated by Django 5.1.6 on 2025-03-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_rename_registration_number_field_staff_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='registration_number',
        ),
    ]
