# Generated by Django 5.1.6 on 2025-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_remove_staff_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='registration_number',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
