# Generated by Django 5.1.6 on 2025-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_staff_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='registration_number',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
