# Generated by Django 4.1.2 on 2025-03-20 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0015_staff_aadhar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="firstname",
            new_name="fullnaame",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="surname",
        ),
    ]
