# Generated by Django 5.2 on 2025-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0017_rename_fullnaame_staff_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="passport",
            field=models.ImageField(blank=True, upload_to="staffs/passports/"),
        ),
    ]
