# Generated by Django 4.1.2 on 2025-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0018_staff_passport"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_login_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
