# Generated by Django 4.1.2 on 2025-07-19 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0020_staff_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
    ]
