# Generated by Django 5.1.3 on 2025-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0020_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='registration_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
