# Generated by Django 5.2 on 2025-06-26 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0020_staff_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
    ]
