# Generated by Django 5.1.3 on 2025-08-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0022_staff_user'),
        ('staffs', '0024_auto_20250721_1026'),
    ]

    operations = [
    ]
