# Generated by Django 4.1.2 on 2025-11-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0025_merge_0022_staff_user_0024_auto_20250721_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
