# Generated by Django 5.1.6 on 2025-03-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonTeachingStaffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='job_role',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
