# Generated by Django 4.1.2 on 2025-03-20 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NonTeachingStaffs", "0002_nonteachingstaff_job_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nonteachingstaff",
            old_name="firstname",
            new_name="fullnaame",
        ),
        migrations.RemoveField(
            model_name="nonteachingstaff",
            name="other_name",
        ),
        migrations.RemoveField(
            model_name="nonteachingstaff",
            name="surname",
        ),
    ]
