# Generated by Django 4.1.2 on 2025-03-20 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "NonTeachingStaffs",
            "0003_rename_firstname_nonteachingstaff_fullnaame_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="nonteachingstaff",
            old_name="fullnaame",
            new_name="fullname",
        ),
    ]
