# Generated by Django 4.1.2 on 2025-11-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NonTeachingStaffs", "0004_rename_fullnaame_nonteachingstaff_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonteachingstaff",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
