# Generated by Django 4.1.2 on 2025-03-20 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendance_studentattendance_delete_student_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentAttendance",
        ),
    ]
