# Generated by Django 4.1.2 on 2025-03-21 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_staffattendance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaffAttendance",
        ),
    ]
