# Generated by Django 4.1.2 on 2025-03-24 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0022_alter_student_options_and_more"),
        ("attendance", "0006_delete_staffattendance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
