# Generated by Django 4.1.2 on 2025-03-24 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
    ]
