# Generated by Django 5.1.6 on 2025-02-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname', 'firstname']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_name',
        ),
    ]
