# Generated by Django 5.1.6 on 2025-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Gen', 'Gen'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST'), ('Other', 'Other')], default='N/A', max_length=10),
        ),
    ]
