# Generated by Django 5.1.6 on 2025-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_parents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Parents_name',
            field=models.CharField(max_length=255),
        ),
    ]
