# Generated by Django 5.1.6 on 2025-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_unique_id_alter_student_father_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
