# Generated by Django 5.1.6 on 2025-03-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_student_unique_id_student_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
    ]
