# Generated by Django 5.1.6 on 2025-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_rename_father_name_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/barcodes/'),
        ),
    ]
