# Generated by Django 5.1.6 on 2025-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/barcodes/'),
        ),
    ]
