# Generated by Django 5.1.6 on 2025-03-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='barcode_image',
        ),
    ]
