# Generated by Django 4.1.2 on 2025-03-10 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0021_remove_student_barcode_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["fullname"]},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="firstname",
            new_name="fullname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="surname",
        ),
    ]
