# Generated by Django 5.2 on 2025-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0024_alter_student_father_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="registration_number",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
