# Generated by Django 5.2 on 2025-04-08 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0026_populate_registration_numbers"),
        ("students", "XXXX_populate_registration_numbers"),
    ]

    operations = []
