# Generated by Django 5.2 on 2025-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0029_remove_studentdocument_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email_id",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
