# Generated by Django 5.2 on 2025-05-08 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_studentudiseinfo"),
        ("students", "0031_studentdocument_address_proof_and_more"),
    ]

    operations = []
